const INTERNAL_SERVER_ERROR = require('./INTERNAL_SERVER_ERROR')
const PAGE_NOT_FOUND_ERROR = require('./PAGE_NOT_FOUND_ERROR')
const BaseError = require('./BaseError')
const AUTH_TOKEN_ERROR = require('./AUTH_TOKEN_ERROR')
const REFRESH_TOKEN_ERROR = require('./REFRESH_TOKEN_ERROR')
const UNAUTH_ERROR = require('./UNAUTH_ERROR')
const DATA_BASE_ERROR = require('./DATABASE_ERROR')
const RESOURCE_ALREADY_EXISTS = require('./RESOURCE_ALREADY_EXISTS')
const INVALID_CREDENTIAL_ERROR = require('./INVALID_CREDENTIAL_ERROR')


module.exports = {
    BaseError,
    INTERNAL_SERVER_ERROR,
    PAGE_NOT_FOUND_ERROR,
    AUTH_TOKEN_ERROR,
    REFRESH_TOKEN_ERROR,
    UNAUTH_ERROR,
    DATA_BASE_ERROR,
    RESOURCE_ALREADY_EXISTS,
    INVALID_CREDENTIAL_ERROR
}